#frontend/nginx.conf
server{
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    #SPA FALLBACK -> ALL NKNOWN PATHS ARE ROUTEX TO INDEX.HTML
    location / {
        try_files $uri $uri/ /index.html;
    }

    #CACHE STATIC ASSETS
    location ~* \.(js|css|png|jpg|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
    # Proxy API calls to FastAPI
    location /api/ {
         proxy_pass http://api:8000/;
    }
}