/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatasetId = number;
export type ChartType = "bar" | "line" | "pie" | "scatter" | "area" | "heatmap" | "kpi";
export type Title = string;
export type XColumn = string | null;
export type YColumn = string | null;
export type Column = string;
export type Operator = "==" | "!=" | ">" | "<" | "in" | "like";
export type Filters = FilterCondition[];
export type GroupBy = string[] | null;
export type AggFunc = ("SUM" | "MEAN" | "COUNT" | "MAX" | "MIN") | null;
export type ValueCol = string | null;
export type Default = "drop" | "fill" | "mean";
export type DefaultFillValue = string | number | null;
export type Overrides = {
  [k: string]: string | MissingOverride;
} | null;
export type Strategy = "drop" | "fill" | "mean";
export type FillValue = string | number | null;
export type ColorScheme = string;

export interface AggregationSpec {
  value_col: string;
  agg_func: "SUM" | "MEAN" | "COUNT" | "MAX" | "MIN";
  alias?: string | null;
}

export interface WidgetConfig {
  dataset_id: DatasetId;
  chart_type: ChartType;
  title: Title;
  x_column?: XColumn;
  y_column?: YColumn;
  filters?: Filters;
  group_by?: GroupBy;
  agg_func?: AggFunc;
  value_col?: ValueCol;
  missing_config?: MissingConfig | null;
  color_scheme?: ColorScheme;
  aggregations?: AggregationSpec[] | null;   // ← NEW

}
export interface FilterCondition {
  column: Column;
  operator: Operator;
  value: Value;
  [k: string]: unknown;
}
export interface Value {
  [k: string]: unknown;
}
/**
 * Top‑level missing value configuration.
 */
export interface MissingConfig {
  default?: Default;
  default_fill_value?: DefaultFillValue;
  overrides?: Overrides;
  [k: string]: unknown;
}
/**
 * Per‑column override for missing value strategy.
 */
export interface MissingOverride {
  strategy: Strategy;
  fill_value?: FillValue;
  [k: string]: unknown;
}

// --- New interfaces for Dashboard API ---

export interface DashboardCreateRequest {
  title: string;
  widgets?: WidgetConfig[] | null;
}

export interface DashboardUpdateRequest {
  title?: string | null;
}

export interface WidgetCreateRequest {
  config: WidgetConfig;
  position?: { [key: string]: any } | null;
}

export interface WidgetUpdateRequest {
  config?: WidgetConfig | null;
  position?: { [key: string]: any } | null;
}

export interface WidgetResponse {
  id: number;
  config: WidgetConfig;
  chart_data: Array<{ [key: string]: any }>;
  position?: { [key: string]: any } | null;
  created_at: string;
  updated_at: string;
}

export interface DashboardResponse {
  id: number;
  title: string;
  widgets: WidgetResponse[];
  created_at: string;
  updated_at: string;
}

export interface DashboardListItem {
  id: number;
  title: string;
  created_at: string;
  widget_count: number;
}
